# Generated by Django 5.2 on 2026-03-18 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0002_remove_post_image_url_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_contents",
                        to="testApp.post",
                    ),
                ),
            ],
        ),
    ]
